# Generated by Django 4.2.6 on 2023-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentVehicle', '0004_auto_20210309_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentvehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
