# Generated by Django 4.2.6 on 2023-11-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerHome', '0006_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_pincode',
        ),
    ]
